spring.application.name=ms-redis

# ===================================================================
# REDIS PROPERTIES
# ===================================================================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.connect-timeout=2s
spring.data.redis.timeout=2s

account-balance.cache.ttl=PT10M
account-balance.cache.key-prefix=account-balances::